name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Test actions
        uses: ./
        with:
          pkgname: 'nonicons-font'
          git-username: ${{ secrets.GIT_USERNAME }}
          git-email: ${{ secrets.GIT_EMAIL }}
          private-ssh-key: ${{ secrets.AUR_PRIVATE_SSH_KEY }}
          push: false
